import S from '@sanity/desk-tool/structure-builder'
import { FaBullhorn, FaCog, FaHome, FaPencilRuler, FaRegFileAlt, FaRegBuilding, FaRegIdCard, FaUserFriends } from "react-icons/fa";

export default () =>
	S.list()
		.title('Content')
		.items([
			S.listItem()
				.title('Settings')
				.icon(FaCog)
				.child(
					S.editor()
						.schemaType('siteSettings')
						.documentId('siteSettings')
				),
			S.divider(),
			S.listItem()
				.title('Pages')
				.icon(FaRegFileAlt)
				.child(
					S.documentTypeList('page').title('Pages')
					),
			S.listItem()
				.title('Blog')
				.icon(FaBullhorn)
				.child(
					S.list()
						.title('Blog')
						.items([
							S.listItem()
								.title('Blog Settings')
								.icon(FaCog)
								.child(
									S.editor()
										.schemaType('blogSettings')
										.documentId('blogSettings')
								),
							S.listItem()
								.title('Posts')
								.schemaType('post')
								.child(S.documentTypeList('post').title('Posts'))
						])
				),
			S.divider(),
			S.listItem()
				.title('Portfolio')
				.icon(FaPencilRuler)
				.child(
					S.list()
						.title('Portfolio')
						.items([
								S.listItem()
									.title('Projects')
									.schemaType('project')
									.child(S.documentTypeList('project').title('Projects')),
								S.listItem()
									.title('Clients')
									.schemaType('client')
									.child(S.documentTypeList('client').title('Clients'))
							])
					),
			S.divider(),
			S.listItem()
				.title('Company Information')
				.icon(FaRegIdCard)
				.child(
					S.editor()
						.schemaType('companyInfo')
						.documentId('companyInfo')
				),
			S.listItem()
				.title('Staff')
				.icon(FaUserFriends)
				.child(
					S.list()
						.title('Staff')
						.items([
								S.listItem()
									.title('Staff Members')
									.icon(FaUserFriends)
									.schemaType('person')
									.child(S.documentTypeList('person').title('Staff Members')),
								S.listItem()
									.title('Roles')
									.schemaType('jobTitle')
									.child(S.documentTypeList('jobTitle').title('Roles'))
							])
					),
			S.listItem()
				.title('Offices')
				.icon(FaRegBuilding)
				.schemaType('office')
				.child(
					S.documentTypeList('office').title('Offices')
					),
			...S.documentTypeListItems().filter(listItem =>
				![
					'blogSettings',
					'client',
					'companyInfo',
					'jobTitle',
					'office',
					'page',
					'person',
					'post',
					'project',
					'siteSettings',
					'socialMediaService'
				].includes(listItem.getId()))
		]
	)
